[env]
TERM = "screen-256color"

[general]
import = ["mellow.toml"]

[window]
decorations = "None"
dynamic_padding = true

[mouse]
hide_when_typing = true

[font]
normal = { family = "MonaspiceNe Nerd Font", style = "Medium" }
size = 20
