[general]
import = ["kanawaga_dragon.toml"]

[window]
decorations = "None"
padding = { x = 8, y = 0}
# opacity = 0.95

[mouse]
hide_when_typing = true

[font]
normal = { family = "MonaspiceNe Nerd Font", style = "Medium" }
size = 20
offset = { x = 0, y = 1 }
