[general]
import = ["kanawaga_dragon.toml"]

[window]
decorations = "None"

[mouse]
hide_when_typing = true

[font]
normal = { family = "MonaspiceNe Nerd Font", style = "Medium" }
size = 20
offset = { x = 0, y = 1 }
