[general]
import = ["rose-pine.toml"]

[window]
decorations = "None"
padding = { x = 8, y = 0}

[mouse]
hide_when_typing = true

[font]
normal = { family = "MonaspiceNe Nerd Font", style = "Medium" }
size = 20
offset = { x = 0, y = 1 }
