save_frequency = 10
log_level = "INFO"

[workspace]
buffer = 30
tau = 604800.0

[workspace.filter]
mode = "Exclude"
programs = ["", "gcr-prompter", "xdg-desktop-portal-gtk"]

[floating]
frequency = 5

[floating.filter]
mode = "Include"
programs = ["org.gnome.Calculator"]

[restore]
timeout = 120

[restore.filter]
mode = "Include"
programs = []
