theme = "kdragon"

[editor]
bufferline = "always"
true-color = true
color-modes = true
cursorline = true
line-number = "relative"
popup-border = "all"
completion-trigger-len = 1
completion-timeout = 50
idle-timeout = 50
scrolloff = 10

[editor.search]
smart-case = true

[editor.soft-wrap]
enable = true
max-wrap = 20 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["version-control","workspace-diagnostics" ]
right = ["diagnostics", "file-type","position-percentage", "total-line-numbers"]

[editor.indent-guides]
render = true
character = "â”†"
skip-levels = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.lsp]
display-messages = true
auto-signature-help = true
display-inlay-hints = true
[editor.file-picker]
hidden = false

[keys.normal]
"+" = ":format"
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"
# Turn inlay hints of when typing and show for reading
i = ["insert_mode", ":set-option lsp.display-inlay-hints false"]
I = ["insert_at_line_start", ":set-option lsp.display-inlay-hints false"]
a = [
  "move_char_right",
  "insert_mode",
  ":set-option lsp.display-inlay-hints false",
]
A = ["insert_at_line_end", ":set-option lsp.display-inlay-hints false"]
o = ["open_below", ":set-option lsp.display-inlay-hints false"]
O = ["open_above", ":set-option lsp.display-inlay-hints false"]

[keys.insert]
# Turn inlay hints off when typing and show for reading
"esc" = ["normal_mode", ":set-option lsp.display-inlay-hints true"]


[keys.normal.space]
x = ":buffer-close"
X = ":buffer-close!"
