theme = "kdragon"

[editor]
bufferline = "always"
true-color = true
color-modes = true
cursorline = true
line-number = "relative"
popup-border = "all"
completion-trigger-len = 1
continue-comments = false
idle-timeout = 250
completion-timeout = 5
scrolloff = 10

[editor.search]
smart-case = true

[editor.soft-wrap]
enable = true
max-wrap = 20
max-indent-retain = 0
wrap-indicator = ""

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["version-control","workspace-diagnostics" ]
right = ["diagnostics", "file-type","position-percentage", "total-line-numbers"]

[editor.indent-guides]
render = true
character = "â”†"
skip-levels = 0

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.lsp]
display-messages = true
auto-signature-help = true
display-inlay-hints = true
[editor.file-picker]
hidden = false

[keys.normal]
"+" = ":format"
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"
# Turn inlay hints of when typing and show for reading
i = ["insert_mode", ":set-option lsp.display-inlay-hints false"]
I = ["insert_at_line_start", ":set-option lsp.display-inlay-hints false"]
a = [
  "move_char_right",
  "insert_mode",
  ":set-option lsp.display-inlay-hints false",
]
A = ["insert_at_line_end", ":set-option lsp.display-inlay-hints false"]
o = ["open_below", ":set-option lsp.display-inlay-hints false"]
O = ["open_above", ":set-option lsp.display-inlay-hints false"]
H = "goto_line_start"
L = "goto_line_end"
J = "page_cursor_half_down"
K = "page_cursor_half_up"

[keys.normal.space]
x = ":buffer-close"
X = ":buffer-close!"
q = ":sh zellij run -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- fx"

[keys.normal.space.n]
n = "@:sh touch "
N = "@:sh touch <C-r>%<C-w>"
d = "@:sh mkdir -p "
D = "@:sh mkdir -p <C-r>%<C-w>"
r = "@:sh rm <C-r>%"
R = "@:sh rm <C-r>%<C-w>"
m = "@:sh mv <C-r>% "
p = "@:sh cp <C-r>% "

[keys.insert]
# Turn inlay hints off when typing and show for reading
"esc" = ["normal_mode", ":set-option lsp.display-inlay-hints true"]

[keys.select]
H = "goto_line_start"
L = "goto_line_end"
J = "page_cursor_half_down"
K = "page_cursor_half_up"
