inherits = "ashen"

"type" = "orange_smolder"
"type.builtin" = "orange_smolder"
"variable.builtin" = { fg = "red_ember", modifiers = ["italic"] }
"constant.numeric" = { fg = "orange_smolder", modifiers = ["bold"] }
"constant.builtin" = { fg = "orange_smolder", modifiers = ["bold"] }
"function.macro" = { fg = "red_ember", modifiers = ["italic"] }


"ui.virtual.whitespace" = { fg = "g_6", modifiers = ["italic", "dim"] }
"ui.virtual.indent-guide" = { fg = "g_6", modifiers = ["italic", "dim"] }
"ui.virtual.wrap" = { fg = "g_6", modifiers = ["italic", "dim"] }
"ui.virtual.inlay-hint" = { fg = "g_6", modifiers = ["italic", "dim"] }
"ui.virtual.inlay-hint.parameter" = { fg = "g_6", modifiers = [
  "italic",
  "dim",
] }
"ui.virtual.inlay-hint.type" = { fg = "g_6", modifiers = ["italic", "dim"] }


# [palette]
# cursorline = "#191919"
# text = "#b4b4b4"
# red_flame = "#C53030"
# red_glowing = "#DF6464"
# red_ember = "#B14242"
# orange_glow = "#D87C4A"
# orange_blaze = "#C4693D"
# orange_muted = "#6D3B22"
# orange_smolder = "#E49A44"
# orange_golden = "#E5A72A"
# golden_muted = "#6D4D0D"
# brown = "#89492a"
# brown_dark = "#322119"
# blue = "#4A8B8B"
# background = "#121212"
# g_1 = "#e5e5e5"
# g_2 = "#d5d5d5"
# g_3 = "#b4b4b4"
# g_4 = "#a7a7a7"
# g_5 = "#949494"
# g_6 = "#737373"
# g_7 = "#535353"
# g_8 = "#323232"
# g_9 = "#212121"
# g_10 = "#1d1d1d"
# g_11 = "#191919"
# g_12 = "#151515"
